### ISSUE TITLE
Link to free Azure account must come before first H2

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#10]
Report shows errors for rule 'Link to free Azure account must come before first H2' even though the link exists before first H2 on the articles

Examples: 
https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-web-app-cache-aside-leaderboard
https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-dotnet-how-to-use-azure-redis-cache

**Comment by craigshoemaker** [comment]
The link to the free Azure account is brought into these articles via an INCLUDE. Supporting includes is a feature that Spinefeed should support. For now, I'm closing this issue and have opened a [new issue to track support for INCLUDES](https://github.com/craigshoemaker/spinefeed-function/issues/12).

cc @mimig1 for visibility
