### ISSUE TITLE
Required metadata: Customer intent statement

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#11]
False positives that have Customer intent statement.
https://github.com/MicrosoftDocs/azure-docs-pr/blob/master/articles/azure-cache-for-redis/cache-dotnet-core-quickstart.md

**FileName**
cache-dotnet-core-quickstart.md
cache-dotnet-how-to-use-azure-redis-cache.md
cache-java-get-started.md
cache-nodejs-get-started.md
cache-web-app-cache-aside-leaderboard.md
cache-web-app-howto.md

**Comment by craigshoemaker** [comment]
Closed by 8796348bc63b4e8f851e022bfc3ec69bcbae0655

cc @mimig1 for visibility
