### ISSUE TITLE
Relative links must end with the ".md" extension

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#13]
False positives on relative links that are mostly ending with .yml

Relative links must   end with the ".md" extension | /azure-docs-pr/articles/azure-government/documentation-government-services-aiandcognitiveservices.md | documentation-government-services-aiandcognitiveservices.md | article | jglixon | jglixon | 10/23/2018
-- | -- | -- | -- | -- | -- | --
Relative links must end with the   ".md" extension | /azure-docs-pr/articles/azure-government/documentation-government-services-database.md | documentation-government-services-database.md | article | zsk0646 | zakramer | 3/6/2019
Relative links must end with the   ".md" extension | /azure-docs-pr/articles/azure-government/documentation-government-services-iot-hub.md | documentation-government-services-iot-hub.md | article | gsacavdm | gsacavdm | 3/30/2018
Relative links must end with the   ".md" extension | /azure-docs-pr/articles/azure-government/documentation-government-services-securityandidentity.md | documentation-government-services-securityandidentity.md | article | gsacavdm | gsacavdm | 3/24/2019
Relative links must end with the   ".md" extension | /azure-docs-pr/articles/azure-government/documentation-government-services-storage.md | documentation-government-services-storage.md | article | zsk0646 | zakramer | 8/15/2017
Relative links must end with the   ".md" extension | /azure-docs-pr/articles/azure-government/documentation-government-services-webandmobile.md | documentation-government-services-webandmobile.md | article | gsacavdm | gsacavdm | 10/28/2018

**Comment by nivnar** [comment]
@craigshoemaker - Could you check the code for relative links ending with .yml? Thanks
https://github.com/craigshoemaker/spinefeed-function/issues/9

**Comment by craigshoemaker** [comment]
Closed by 743f29c168ce214ba0d3b861625dc621122ec8d0

I also added improved logic to filter out code blocks that resemble relative links, support for email address links
