### ISSUE TITLE
New Feature : Add ms.service and ms.subservice columns in results

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#14]
@craigshoemaker - Some content sets TOCs are nested within a larger TOC.

Each smaller TOC will be owned by a different team. Audit results can be filtered and communicated to teams based on ms.subservice values. It would be helpful to add metadata values as two new columns in the output.
1. ms.service
2. ms.subservice

Example of content set nested within larger content set:
https://docs.microsoft.com/en-us/power-bi/power-bi-custom-visuals

**Comment by craigshoemaker** [comment]
This new feature is complete, but I am closing this issue. I created a new issue over in the Spinefeed Client repo, as this feature request really belongs there. 

See #10 in the Spinefeed Client repo:

https://github.com/craigshoemaker/spinefeed-client/issues/10
