### ISSUE TITLE
Rule - Next step action formatted link is required after Next steps title

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#3]
Almost all the audit results were false positive. Articles have Button or link after 'Next Steps' title.

- articles/mysql/connect-cpp.md
- articles/mysql/connect-csharp.md
- articles/mysql/quickstart-create-mysql-server-database-using-azure-cli.md
- articles/mysql/quickstart-create-mysql-server-database-using-azure-portal.md
- articles/mysql/tutorial-design-database-using-cli.md
- articles/mysql/tutorial-design-database-using-portal.md
- articles/mysql/tutorial-provision-mysql-server-using-Azure-Resource-Manager-templates.md

**Comment by craigshoemaker** [comment]
Commit d3f03384f99c42c63052af1969231d3fa2fd8993 addresses this issue.

**Comment by nivnar** [comment]
@craigshoemaker - In the audit that I ran today, this issue resurfaced. Articles have action formatted link under Next Steps. 
https://review.docs.microsoft.com/en-us/azure/virtual-desktop/create-host-pools-azure-marketplace?branch=release-preview-virtual-desktop#next-steps

azure-docs-pr/articles/virtual-desktop/create-host-pools-azure-marketplace.md
azure-docs-pr/articles/virtual-desktop/manage-app-groups.md
azure-docs-pr/articles/virtual-desktop/tenant-setup-azure-active-directory.md

**Comment by nivnar** [comment]
@craigshoemaker - Are you able to fix this bug sometime this week? Thanks

**Comment by craigshoemaker** [comment]
closed by 41ff1551349afe346dd9220eec85bec225444f37
