### ISSUE TITLE
Possible duplicate rules for checklist requirement for tutorial before first H2

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#4]
There could be duplicate versions of the same rule as

- Checklist must appear before first H2 (might be valid)
- Checklist is required
- Checklist is required after paragraph that contains "In this tutorial"

Example:

Rule | FilePath
-- | --
Checklist must appear before   first H2 | articles/api-management/add-api-manually.md
Checklist is required | articles/api-management/add-api-manually.md
Checklist is required after   paragraph that contains "In this tutorial" | articles/api-management/add-api-manually.md

**Comment by craigshoemaker** [comment]
I think these are all valid. The first one makes sure the checklist is in the article and the other two deal with the placement in the article.

I'll reorder them a bit to explain:

1. **Checklist is required**: Ensures there is a checklist in a tutorial.

2. **Checklist must appear before first H2 (might be valid)**: Ensures that the checklist appears *before* the first H2.

3. **Checklist is required after paragraph that contains "In this tutorial"**: Ensures that the checklist appears *after* the first paragraph that contains the text "In this tutorial".
