### ISSUE TITLE
Rule - Checklist is required after paragraph that contains "In this tutorial"

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#5]
False positives on this rule across articles. 

https://docs.microsoft.com/en-us/azure/api-management/api-management-customize-styles
![image](https://user-images.githubusercontent.com/36546471/53442359-001d4b00-39be-11e9-9295-200faacb843c.png)

Examples:
articles/api-management/api-management-customize-styles.md
articles/api-management/api-management-get-started-publish-versions.md
articles/api-management/api-management-get-started-revise-api.md
articles/api-management/api-management-howto-add-products.md
articles/api-management/api-management-howto-api-inspector.md
articles/api-management/api-management-howto-use-azure-monitor.md
articles/api-management/import-and-publish.md
articles/api-management/import-function-app-as-api.md
articles/api-management/mock-api-responses.md
articles/api-management/transform-api.md

**Comment by craigshoemaker** [comment]
Closed by:

- ca2f69eeaec3e5290e5dd7b30993be05e3bd1189
- 361787a69299a15b6fa47de826401c126bf1f619
- 5e88ec225e0006dd4bea4567ccc70ab386362cd1
