### ISSUE TITLE
Rule - Required sentence after intro paragraph: "In this tutorial"

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#6]
False positives on rule 'Required sentence after intro paragraph: "In this tutorial"'

https://docs.microsoft.com/en-us/azure/api-management/api-management-get-started-publish-versions
![image](https://user-images.githubusercontent.com/36546471/53442572-715cfe00-39be-11e9-9229-87e20fd9cece.png)

Examples:
/articles/api-management/api-management-customize-styles.md
/articles/api-management/api-management-get-started-publish-versions.md
/articles/api-management/api-management-get-started-revise-api.md
/articles/api-management/api-management-howto-add-products.md
/articles/api-management/api-management-howto-api-inspector.md
/articles/api-management/api-management-howto-use-azure-monitor.md
/articles/api-management/import-and-publish.md
/articles/api-management/mock-api-responses.md
/articles/api-management/transform-api.md

**Comment by craigshoemaker** [comment]
Closed by 47d7bdc3b060a4b2e22e4f3cf56efd73aded89d7
