### ISSUE TITLE
Rule - Introductory sentence must be no more than 6 sentences.

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#7]
Possible false positives on rule as few introductory para have <6 sentences

https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-add-products
![image](https://user-images.githubusercontent.com/36546471/53446746-83dc3500-39c8-11e9-93d6-064a0c01ce60.png)

Examples:
articles/api-management/api-management-howto-add-products.md
articles/api-management/api-management-howto-use-azure-monitor.md
articles/api-management/import-api-app-as-api.md
articles/api-management/import-function-app-as-api.md
articles/api-management/import-logic-app-as-api.md

**Comment by nivnar** [comment]
@craigshoemaker - Did you get a chance to look into this issue?

**Comment by craigshoemaker** [comment]
Closed by dea13c74b13d42b46142f5afce26b043159a3220
