### ISSUE TITLE
Rule - Required section: "Clean up resources"

### ISSUE THREAD

**Issue by nivnar** [craigshoemaker/spinefeed-function#8]
Few articles are flagged even though clean up section exists on the article.
Its could be due to an include file for this section as [!INCLUDE Cleanup] 

Examples:
/articles/azure-signalr/signalr-quickstart-azure-functions-csharp.md
/articles/azure-signalr/signalr-quickstart-azure-functions-javascript.md
/articles/azure-signalr/signalr-quickstart-rest-api.md

**Comment by craigshoemaker** [comment]
Closed by 172a215554c834f3d235b399f388899905e5a2e5
